// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvpFjfoz2GkNawwVCZgjrxd9atHF9lu6s',
    appId: '1:186698770372:web:35fcaba8367e983e176691',
    messagingSenderId: '186698770372',
    projectId: 'flutterapp-kris',
    authDomain: 'flutterapp-kris.firebaseapp.com',
    storageBucket: 'flutterapp-kris.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMDUj6m0-kdjQOF9xUliJuTp9KJEw3WE',
    appId: '1:186698770372:android:0a319d450c670f11176691',
    messagingSenderId: '186698770372',
    projectId: 'flutterapp-kris',
    storageBucket: 'flutterapp-kris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATt90eOvE4lkQJUOgmoKfL2he2p70ALGw',
    appId: '1:186698770372:ios:bedcd86252d3f1de176691',
    messagingSenderId: '186698770372',
    projectId: 'flutterapp-kris',
    storageBucket: 'flutterapp-kris.appspot.com',
    iosBundleId: 'com.example.firebaseApp3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATt90eOvE4lkQJUOgmoKfL2he2p70ALGw',
    appId: '1:186698770372:ios:bedcd86252d3f1de176691',
    messagingSenderId: '186698770372',
    projectId: 'flutterapp-kris',
    storageBucket: 'flutterapp-kris.appspot.com',
    iosBundleId: 'com.example.firebaseApp3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvpFjfoz2GkNawwVCZgjrxd9atHF9lu6s',
    appId: '1:186698770372:web:636e5301c46f10f2176691',
    messagingSenderId: '186698770372',
    projectId: 'flutterapp-kris',
    authDomain: 'flutterapp-kris.firebaseapp.com',
    storageBucket: 'flutterapp-kris.appspot.com',
  );
}
